SDET-U8
timsBt/UIautotests pull request #11
Opened 2023-05-07 20:59 UTC by timsBt

Задача U8. Перезапуск упавших тестов

2023-05-09 23:22 UTC, I-DV requested changes

2023-05-09 23:22 UTC, I-DV commented on src/test/java/tests/FailedTestCases.java
> +        failedTestCases.add("C:\\Users\\timsb\\IdeaProjects\\UIautotests\\test-output\\testng-failed.xml");
+ папка test-output вроде создается только если ты с идее запускашь с дефолтным репортером, верно?

2023-05-09 23:22 UTC, I-DV commented on src/test/java/tests/FailedTestCases.java
> +    }
+ желательно чтобы у тебя была xml конфигурация и можно было перезапустить еще и упавшие при прогоне конфигурации

2023-05-09 23:22 UTC, I-DV commented on testsOnTestngFailed.bat
> +java -cp "C:\Users\timsb\IdeaProjects\UIautotests\out\artifacts\UIautotests_jar/*" org.testng.TestNG test-output/testng-failed.xml
это тоже не могу проверить

2023-05-11 08:20 UTC, I-DV requested changes
Добавить профили maven, чтобы активацией профиля можно было перезапустить упавшие тесты

2023-05-11 08:20 UTC, I-DV commented on testsOnTestngFailed.bat
> +mvn clean test -DsuiteXmlFile="test-output/testng-failed.xml"
тут думаю тоже лучше на профили лучше перевести

2023-05-11 08:20 UTC, I-DV commented on pom.xml
> +                    <reportsDirectory>${basedir}/test-output</reportsDirectory>
все, что генерируется давай будем хранить в папке target

2023-05-12 18:33 UTC, I-DV requested changes

2023-05-12 18:33 UTC, I-DV commented on pom.xml
> +                                    <value>${project.build.directory}/allure-results</value>
Это не совсем правильный подход, т.к. ты можешь профили прописать отдельно не дергая плагин, например:
`<profiles>
        <profile>
            <id>smoke_tests</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>smoke</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <suiteXmlFileName>tests_default.xml</suiteXmlFileName>
            </properties>
        </profile>
     </profiles>`
     
     Остается только в surefire-plugin динамически определять xml - конфигурацию

2023-05-12 19:49 UTC, timsBt commented on pom.xml
> +                                    <value>${project.build.directory}/allure-results</value>
Спасибо, так намного лучше, нет громадного повторяющегося кода)

2023-05-15 17:02 UTC, I-DV requested changes
Поправить pom, прочитай еще раз про профили мавен

2023-05-15 17:02 UTC, I-DV commented on pom.xml
> +                <activeByDefault>true</activeByDefault>
этот профиль не должен быть активен по дефолту

2023-05-15 17:02 UTC, I-DV commented on pom.xml
> +                <suiteXmlFileName>test-output/testng-failed.xml</suiteXmlFileName>
если попробуешь запустить с командой mvn clean test, то поймешь, что такого пути нет

2023-05-16 16:48 UTC, I-DV approved these changes
Обсудили на созвоне

2023-05-16 18:23 UTC, merged