SDET U10
timsBt/UIautotests pull request #12
Opened 2023-05-08 20:34 UTC by timsBt

Задача U10. Drag n Drop (IFrame)

2023-05-11 08:37 UTC, I-DV requested changes

2023-05-11 08:37 UTC, I-DV commented on src/test/java/tests/DragAndDropTest.java
> +    public void setgetDriver() {
мне не нравится название метода. Может быть "openPage"?

2023-05-11 08:37 UTC, I-DV commented on src/test/java/tests/DragAndDropTest.java
> +    public void setgetDriver() {
поменяй везде это

2023-05-11 08:37 UTC, I-DV commented on src/test/java/tests/DragAndDropTest.java
> +    public static final String DROPPBLE_URL = "http://way2automation.com/way2auto_jquery/droppable.php";
если строка используется только в этом классе, то нет необходимости ее делать статической. исправь везде

2023-05-11 08:37 UTC, I-DV commented on src/test/java/tests/DragAndDropTest.java
> +        Assert.assertNotEquals(dragAndDropPage.getTextDropp(), valueProperties("dropText"));
не обязательно везде использовать метод valueProperties, тут ты можешь прямо в ассерте написать текст

2023-05-11 08:37 UTC, I-DV commented on src/test/java/tests/DragAndDropTest.java
> +        Assert.assertNotEquals(dragAndDropPage.getTextDropp(), valueProperties("dropText"));
и еще поменяй на assertEquals

2023-05-11 16:32 UTC, timsBt commented on src/test/java/tests/DragAndDropTest.java
> +    public void setgetDriver() {
точно, так лучше)

2023-05-11 16:32 UTC, timsBt commented on src/test/java/tests/DragAndDropTest.java
> +        Assert.assertNotEquals(dragAndDropPage.getTextDropp(), valueProperties("dropText"));
ок, понял)

2023-05-12 18:34 UTC, I-DV approved these changes

2023-05-13 02:01 UTC, merged