SDET-U9
timsBt/UIautotests pull request #14
Opened 2023-05-13 01:34 UTC by timsBt

Задача U9. Браузеры

2023-05-15 22:59 UTC, I-DV requested changes
В целом все нормально. Нужно поправить файл конфигурации и добавить профили в pom

2023-05-15 22:59 UTC, I-DV commented on SeleniumGridScripts/nodeconfig.toml
> +max-sessions = 80
не много? Обычно по количеству ядер машины выставляют)

2023-05-15 22:59 UTC, I-DV commented on src/test/java/tests/BaseTest.java
> +        driver.get().close();
почему тут close()?

2023-05-15 22:59 UTC, I-DV commented on testng.xml
> +        <parameter name="Remote" value="true"/>
предлагаю тебе сделать профили для удаленного и локального запуска. Чтобы ты мог этой конфигурацией локально запустить кросс-браузерное тестирование

2023-05-15 22:59 UTC, I-DV commented on testng.xml
> +</suite>
пустой строки не хватает

2023-05-16 09:39 UTC, timsBt commented on SeleniumGridScripts/nodeconfig.toml
> +max-sessions = 80
Я думал max-sessions это общее количество тестов на всех браузерах

2023-05-16 09:43 UTC, timsBt commented on testng.xml
> +        <parameter name="Remote" value="true"/>
Ок.понял)

2023-05-16 09:45 UTC, timsBt commented on testng.xml
> +</suite>
Проморгал)

2023-05-18 21:43 UTC, I-DV requested changes
Поправить ошибки по чекстайлу + у меня один тест стабильно падает при любой конфигурации. разберись с ним

![изображение](https://github.com/timsBt/UIautotests/assets/88798787/349b5477-0132-4cc9-a60f-b79421feef57)

2023-05-18 21:43 UTC, I-DV commented on testngParallelMethods.xml
> +<?xml version="1.0" encoding="UTF-8"?>
лишние конфигурации лучше удалить

2023-05-18 21:43 UTC, I-DV commented on localStartBrowsers.xml
> +        <parameter name="Remote" value="false"/>
если у тебя Remote по дефолту false, то зачем прописывать?

2023-05-18 21:43 UTC, I-DV commented on src/test/java/drivers/DriverFactory.java
>  import java.net.MalformedURLException;
![изображение](https://github.com/timsBt/UIautotests/assets/88798787/d4911af7-0fd1-480a-bf85-585a1e848e06)
И так во всех классах. Поправь согласно чекстайлу

2023-05-18 22:01 UTC, timsBt commented on localStartBrowsers.xml
> +        <parameter name="Remote" value="false"/>
ну да. не нужно.

2023-05-21 20:37 UTC, I-DV approved these changes
![изображение](https://github.com/timsBt/UIautotests/assets/88798787/04509cee-5171-431a-8d6f-552195bb7fdd)
Вот так можно решить ошибку чекстайла с утилитным классом

2023-05-21 22:51 UTC, merged