SDET-U14
timsBt/UIautotests pull request #17
Opened 2023-05-21 23:34 UTC by timsBt

Задача U14. BDD практики в тестировании

2023-05-22 22:14 UTC, I-DV requested changes
Исправить замечания, посмотреть ошибки чекстайла, добавить драйверы (без них не запустятся тесты)

2023-05-22 22:14 UTC, I-DV commented on src/test/resources/autorization.feature
> +# language: ru
Файл нужно перенести из ресурсов, т.к это твой тестовый сценарий. Логичнее всего создать папку cucumber и все фичи хранитть там

2023-05-23 05:11 UTC, timsBt commented on src/main/resources/aplication.properties
> +mainPageUrl = https://www.way2automation.com/angularjs-protractor/registeration/#/login
Урлы длинные, чекстайл ругался, а делить по строкам их, что то мне не захотелось) Мне показалось что так удобнее и читабельнее)

2023-05-23 05:12 UTC, timsBt commented on src/test/resources/autorization.feature
> +    Тогда Появилось сообщение об ошибке
Ок

2023-05-23 05:13 UTC, timsBt commented on src/test/resources/autorization.feature
> +# language: ru
Ок,понял)

2023-05-23 19:04 UTC, I-DV commented on src/main/resources/aplication.properties
> +mainPageUrl = https://www.way2automation.com/angularjs-protractor/registeration/#/login
ну в целом ничего страшного, пока они используются по 1 разу. но как только тебе нужно будет использовать их постоянно, то лучше будет их держать в классах

2023-05-23 19:14 UTC, I-DV approved these changes

2023-05-23 19:50 UTC, merged