SDET-D1
timsBt/UIautotests pull request #18
Opened 2023-05-31 22:44 UTC by timsBt

Задача D1. Тестирование API: работа с БД

2023-06-04 01:02 UTC, I-DV reviewed
один момент

2023-06-04 01:03 UTC, I-DV requested changes
Вынести запросы где не переиспользуется и добавить удаление тестовых постов после теста

2023-06-04 09:09 UTC, timsBt commented on src/test/java/api/steps/PostStep.java
> +    }
ok

2023-06-05 06:56 UTC, I-DV approved these changes

2023-06-05 17:28 UTC, merged