SDET-U2
timsBt/UIautotests pull request #5
Opened 2023-04-25 21:22 UTC by timsBt

Allure report. Аннотации Severity, Step, Epic, Feature, Story, Description

2023-04-26 17:39 UTC, I-DV requested changes

2023-04-26 17:39 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +    @Description("Авторизация с одним символом Username")
Мне кажется, что тут скорее Major

2023-04-26 17:39 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +    @Description("Авторизация с валидными данными")
все описания запиши так-же в аннотацию тест пожалуйста. @Test(description = "")

2023-04-26 17:39 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +    @Story(value = "Валидные значения")
Аннотации можно использовать не только на тест, но и на целый класс.
В данном случае подумай как ты будешь группировать тесты в отчете.  Допустим у тебя проект содержит и UI и API тесты. Значит ты можешь Epic использовать для обозначения хоста допустим или вида тестов.

2023-04-26 18:45 UTC, I-DV requested changes

2023-04-26 18:45 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +        HomeLogin homeLogin = new HomeLogin(driver);
А почему решил сюда перенести?

2023-04-26 18:45 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +    @Severity(value = SeverityLevel.MINOR)
Почему minor?

2023-04-26 18:57 UTC, timsBt commented on src/test/java/tests/AuthorizationTest.java
> +    @Severity(value = SeverityLevel.MINOR)
Normal. перепутал. Значительная.

2023-04-26 19:50 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +        HomeLogin homeLogin = new HomeLogin(driver);
у меня на TestNG все нормально проходит. посмотри в чем проблема

2023-04-27 17:50 UTC, I-DV requested changes

2023-04-27 17:50 UTC, I-DV commented on src/main/resources/aplication.properties
> + oneSymbolMessagePassword = Your username must be between 3 and 100 characters long
тут тоже на строку ругается

2023-04-27 17:50 UTC, I-DV commented on src/test/java/pages/HomeLogin.java
> +}
пробелы в методах не на своих местах. 
`public void methodName(Parameters parameters) {
...
}`

2023-04-27 17:50 UTC, I-DV commented on src/test/java/pages/MainPage.java
> +    }
методы повторяются + пробелы

2023-04-27 17:50 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
> +import io.qameta.allure.*;
все импорты раскрываем

2023-04-27 17:50 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
>                  .userName2Input(valueProperties("username2"))
почему тут отступы на 8 пробелов? и ниже тоже

2023-04-27 17:50 UTC, I-DV commented on src/test/java/tests/AuthorizationTest.java
>          Assert.assertEquals(mainPage.textCheckErrorMessage(),valueProperties("errorMessage"));
после запятой пробел при передаче параметров

2023-04-28 20:45 UTC, I-DV approved these changes
небольшие правки

2023-04-28 20:45 UTC, I-DV commented on src/test/java/pages/HomeLogin.java
> +    public String textCheck(){
а вот пробел после скобок нужен

2023-04-28 20:45 UTC, I-DV commented on src/test/java/pages/HomeLogin.java
> +    public String textCheck2(){
тут тоже.  Поправь пожалуйста по всем классам

2023-04-29 09:29 UTC, merged