SDET - U5
timsBt/UIautotests pull request #8
Opened 2023-04-29 21:15 UTC by timsBt

Задача U5. Cookies

2023-04-30 21:30 UTC, I-DV requested changes

2023-04-30 21:30 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +    @Test(description = "Авторизация с помощью cookies из файла", priority = 2)
Что будет если я запущу не весь класс, а только этот тест? Подумай как можно исправить падение теста

2023-04-30 21:30 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +            .emptyButtonClick();
вот теперь ты можешь объединить этот шаг

2023-04-30 21:30 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +    @Story(value = "Значения cookies")
тут наверное можно просто "Cookies"

2023-04-30 21:30 UTC, I-DV commented on src/test/java/utils/CookiesFiles.java
> +public class CookiesFiles {
Давай именовать утилитные классы с припиской Utils...CookiesUtils, PropertiesUtils  и т.д

2023-05-02 21:53 UTC, I-DV requested changes
Поправить тест

2023-05-02 21:53 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
>      }
судя по заданию, то у нас должен быть один тест, который при первом запуске авторизуется с кредов, а при повторном с помощью куков

`Написать тест, авторизующийся при первом запуске и использующий куки при втором (куки брать из предыдущего прогона)`

2023-05-05 20:29 UTC, I-DV requested changes
пару моментов

2023-05-05 20:29 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +    private File file = new File("C:\\Users\\timsb\\IdeaProjects\\UIautotests\\Cookies.data");
с таким путем у меня не запустится) в CI тоже)

2023-05-05 20:29 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +            cookiesUtils.fileWrite();
куки пишутся только после проверки удачной авторизации

2023-05-05 20:29 UTC, I-DV commented on src/test/java/utils/CookiesUtils.java
>      public void fileWrite() {
старайся методы называть более подробно - "writeCookieToFile", "readCookieFromFile"

2023-05-05 20:29 UTC, I-DV commented on src/test/java/utils/CookiesUtils.java
> +}
гит ругается на пустую строку

2023-05-05 20:32 UTC, timsBt commented on src/test/java/tests/CookiesAutorizationTest.java
> +    private File file = new File("C:\\Users\\timsb\\IdeaProjects\\UIautotests\\Cookies.data");
забыл поправить перед пушем)

2023-05-05 20:47 UTC, I-DV requested changes

2023-05-05 20:47 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +    public void getDriver() {
что тебе помешало сделать это в тесте?

2023-05-05 20:47 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +            Assert.assertEquals(sqlPage.textName(), valueProperties("name"));
эта часть теста не работает, т.к. у тебя страница остается авторизованной.

2023-05-09 21:00 UTC, I-DV approved these changes
Поправь замечание и проверь по шагам, что логинится каждый с чистой страницы

2023-05-09 21:00 UTC, I-DV commented on src/test/java/tests/CookiesAutorizationTest.java
> +            sqlPage.logOut();
окей, тут ты выходишь, а когда залогинился с куки - нет.

2023-05-10 21:22 UTC, merged